CREATE TABLE agenda_sets(
   agenda    VARCHAR(128) NOT NULL
  ,expansion VARCHAR(128) NOT NULL
  ,name      VARCHAR(128) NOT NULL
);
INSERT INTO agendas(agenda,expansion,name) VALUES ('Lord Vader''s Command','Core Set','Dark Obsession');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Lord Vader''s Command','Core Set','A Dark Power');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Lord Vader''s Command','Core Set','As You Wish');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Industry','Core Set','Means of Production');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Industry','Core Set','Restorative Supplies');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Industry','Core Set','Interrogation Protocol');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Retaliation','Core Set','Breaking Point');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Retaliation','Core Set','Tactical Explosives');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Retaliation','Core Set','Weakness Revealed');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Agents of the Empire','Core Set','Impounded');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Agents of the Empire','Core Set','Imperial Informants');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Agents of the Empire','Core Set','Tracking Beacon');
INSERT INTO agendas(agenda,expansion,name) VALUES ('For the Right Price','Core Set','Wanted');
INSERT INTO agendas(agenda,expansion,name) VALUES ('For the Right Price','Core Set','High-Value Target');
INSERT INTO agendas(agenda,expansion,name) VALUES ('For the Right Price','Core Set','Hired Help');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Discipline','Core Set','Fire at Will');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Discipline','Core Set','Impending Doom');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Discipline','Core Set','Tactical Maneuvering');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Security Bureau','Core Set','Internal Affairs');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Security Bureau','Core Set','ISB Enforcers');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Security Bureau','Core Set','Imperial Operative');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The General''s Scheme','General Weiss Villain Pack','Forest Ambush');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The General''s Scheme','General Weiss Villain Pack','Inspiring Command');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The General''s Scheme','General Weiss Villain Pack','Special Modifications');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Crimson Empire','Royal Guard Champion Villain Pack','Infection');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Crimson Empire','Royal Guard Champion Villain Pack','Best of the Best');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Crimson Empire','Royal Guard Champion Villain Pack','Pulling the Strings');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Droid Uprising','IG-88 Villain Pack','Binary Revolution');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Droid Uprising','IG-88 Villain Pack','Sabotaged Plans');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Droid Uprising','IG-88 Villain Pack','Firepower Upgrade');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Pursuit of the Enemy','Twin Shadows','Death Mark');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Pursuit of the Enemy','Twin Shadows','Fire in the Sky');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Pursuit of the Enemy','Twin Shadows','Strike and Subdue');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Empire''s Reach','Twin Shadows','Advanced Prototypes');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Empire''s Reach','Twin Shadows','Data Security');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Empire''s Reach','Twin Shadows','Infiltrated');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Stormtrooper Support','Kayn Somos Villain Pack','Perpetual Reinforcements');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Stormtrooper Support','Kayn Somos Villain Pack','Military Presence');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Stormtrooper Support','Kayn Somos Villain Pack','Strength of Command');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Soldiers for Hire','Boba Fett Villain Pack','By Any Means Necessary');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Soldiers for Hire','Boba Fett Villain Pack','No Disintegrations');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Soldiers for Hire','Boba Fett Villain Pack','Predator and Prey');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Vader''s Fist','Stormtroopers Villain Pack','Bunker Buster');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Vader''s Fist','Stormtroopers Villain Pack','Set for Stun');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Vader''s Fist','Stormtroopers Villain Pack','To the Last Man');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Nefarious Dealings','Hired Guns Villain Pack','Back-Room Bargains');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Nefarious Dealings','Hired Guns Villain Pack','Final Blast');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Nefarious Dealings','Hired Guns Villain Pack','Trade Routes Disrupted');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Tusken Treachery','Bantha Rider Villain Pack','Grievous Wound');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Tusken Treachery','Bantha Rider Villain Pack','Into the Wastes');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Tusken Treachery','Bantha Rider Villain Pack','Relocated');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Natural Warfare','Return to Hoth','Bestial Fury');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Natural Warfare','Return to Hoth','Exposed to the Elements');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Natural Warfare','Return to Hoth','Unchained');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Defensive Tactics','Return to Hoth','Counter-Strike');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Defensive Tactics','Return to Hoth','Enhanced Armor');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Defensive Tactics','Return to Hoth','Personal Shield Generators');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Bombardment','General Sorin Villain Pack','Armored Division');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Bombardment','General Sorin Villain Pack','Explosive Shrapnel');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Bombardment','General Sorin Villain Pack','Fully Charged');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Punishing Tactics','Dengar Villain Pack','A Bounty Protected');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Punishing Tactics','Dengar Villain Pack','Beaten Down');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Punishing Tactics','Dengar Villain Pack','Targeted Cruelty');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Enhanced Interrogation','The Bespin Gambit','Blackmail');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Enhanced Interrogation','The Bespin Gambit','Learn Their Weaknesses');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Enhanced Interrogation','The Bespin Gambit','Weak Links');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Evasive Maneuvers','The Bespin Gambit','Contingency Plan');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Evasive Maneuvers','The Bespin Gambit','Feigned Retreat');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Evasive Maneuvers','The Bespin Gambit','Hasty Ambush');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Intelligence','Agent Blaise Villain Pack','Classified Techniques');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Intelligence','Agent Blaise Villain Pack','Security Breach');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Imperial Intelligence','Agent Blaise Villain Pack','Under Surveillance');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Infiltration','ISB Infiltrators Villain Pack','Misdirection');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Infiltration','ISB Infiltrators Villain Pack','Quiet Entry');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Infiltration','ISB Infiltrators Villain Pack','Trip Mine');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Base Instincts','Bossk Villain Pack','Furious Retaliation');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Base Instincts','Bossk Villain Pack','Gunrunner');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Base Instincts','Bossk Villain Pack','On the Hunt');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Contract Gunmen','Greedo Villain Pack','Hunter for a Fee');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Contract Gunmen','Greedo Villain Pack','Stealth Squad');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Contract Gunmen','Greedo Villain Pack','Top Target');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Inquisition','The Grand Inquisitor Villain Pack','Cornered');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Inquisition','The Grand Inquisitor Villain Pack','Targeted by the Empire');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Inquisition','The Grand Inquisitor Villain Pack','When They Least Expect It');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Guild Hunters','Jabba''s Realm','Abandon Contract');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Guild Hunters','Jabba''s Realm','Call Your Shot');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Guild Hunters','Jabba''s Realm','Shoot First');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Persistence','Jabba''s Realm','Jetpacks');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Persistence','Jabba''s Realm','No Rest for the Weary');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Persistence','Jabba''s Realm','Snap Fire');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Wasteland Patrol','Captain Terro Villain Pack','Dewback Patrol');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Wasteland Patrol','Captain Terro Villain Pack','Flamethrower');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Wasteland Patrol','Captain Terro Villain Pack','The Anchorhead Affair');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Jabba''s Empire','Jabba the Hutt Villain Pack','Head-Hunting');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Jabba''s Empire','Jabba the Hutt Villain Pack','One Fat Slug');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Jabba''s Empire','Jabba the Hutt Villain Pack','On Jabba''s Orders');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Desert Scavengers','Jawa Scavenger Villain Pack','Ion Blasters');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Desert Scavengers','Jawa Scavenger Villain Pack','Jawa Raid');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Desert Scavengers','Jawa Scavenger Villain Pack','Salvage Operatives');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Devious Droids','BT-1 and 0-0-0 Villain Pack','Etiquette and Torture');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Devious Droids','BT-1 and 0-0-0 Villain Pack','Invasive Procedure');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Devious Droids','BT-1 and 0-0-0 Villain Pack','Missile Salvo');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Field Commander','Heart of the Empire','Assault Coordination');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Field Commander','Heart of the Empire','Reinforcements En Route');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Field Commander','Heart of the Empire','Unyielding Dedication');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Security Protocols','Heart of the Empire','Heavy Riot Gear');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Security Protocols','Heart of the Empire','Shields Online');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Security Protocols','Heart of the Empire','Surveillance Cams');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Emperor''s Plots','Emperor Palpatine Villain Pack','For the Emperor');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Emperor''s Plots','Emperor Palpatine Villain Pack','Insidious');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Emperor''s Plots','Emperor Palpatine Villain Pack','Isolation');
INSERT INTO agendas(agenda,expansion,name) VALUES ('A Former Sith','Maul Villain Pack','Critical Strikes');
INSERT INTO agendas(agenda,expansion,name) VALUES ('A Former Sith','Maul Villain Pack','Dubious Disposition');
INSERT INTO agendas(agenda,expansion,name) VALUES ('A Former Sith','Maul Villain Pack','Imminent Reprisal');
INSERT INTO agendas(agenda,expansion,name) VALUES ('War of Attrition','Tyrants of Lothal','Acceptable Margins');
INSERT INTO agendas(agenda,expansion,name) VALUES ('War of Attrition','Tyrants of Lothal','Costly Victory');
INSERT INTO agendas(agenda,expansion,name) VALUES ('War of Attrition','Tyrants of Lothal','Selfless Devotion');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Weapons Division','Tyrants of Lothal','Gas Canisters');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Weapons Division','Tyrants of Lothal','Ongoing Research');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Weapons Division','Tyrants of Lothal','Prototypes');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Ohnaka Gang','Hondo Ohnaka Villain Pack','Final Offer');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Ohnaka Gang','Hondo Ohnaka Villain Pack','Missing Treasure');
INSERT INTO agendas(agenda,expansion,name) VALUES ('Ohnaka Gang','Hondo Ohnaka Villain Pack','The Pirate''s Ploy');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Art of War','Thrawn Villain Pack','Piece By Piece');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Art of War','Thrawn Villain Pack','The Admiral''s Grip');
INSERT INTO agendas(agenda,expansion,name) VALUES ('The Art of War','Thrawn Villain Pack','Three Steps Ahead');
