CREATE TABLE hero_items(
   id INTEGER PRIMARY KEY
  ,hero VARCHAR(32) NOT NULL
  ,name VARCHAR(64) NOT NULL
);
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Plasteel Staff');
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Force Adept');
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Force Throw');
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Battle Meditation');
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Defensive Stance');
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Art of Movement');
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Snap Kick');
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Dancing Weapon');
INSERT INTO hero_items(hero,name) VALUES ('Diala Passil','Way of the Sarlacc');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Infantry Rifle');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Tactical Movement');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Take Cover (Fenn)');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Adrenaline Rush');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Weapon Expert');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Suppressive Fire');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Trench Fighter');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Rebel Elite');
INSERT INTO hero_items(hero,name) VALUES ('Fenn Signis','Superior Positioning');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Vibro-Ax');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Wookiee Fortitude');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Wookiee Loyalty');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Ferocity (Gaarkhan)');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Staggering Blow');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Vicious Strike');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Rampage');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Unstoppable');
INSERT INTO hero_items(hero,name) VALUES ('Gaarkhan','Brutal Cleave');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','Holdout Blaster');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','Called Shot');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','Military Efficiency');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','Air of Command');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','Mobile Tactician');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','For the Cause!');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','Rallying Shout');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','Hammer and Anvil');
INSERT INTO hero_items(hero,name) VALUES ('Gideon Argus','Master Stroke');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Vintage Blaster');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Quick as a Whip');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Smuggler''s Luck');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Cheap Shot');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Roll with It');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Get Cocky');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Gunslinger');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Sidewinder');
INSERT INTO hero_items(hero,name) VALUES ('Jyn Odan','Trick Shot');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','Longblaster');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','Disengage');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','Supply Network');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','Jeswandi Training');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','Target Acquired');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','Execute');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','Expertise');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','Decoy');
INSERT INTO hero_items(hero,name) VALUES ('Mak Eshka''rey','No Escape');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Repeating Blaster');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Advance');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Shake It Off');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Crushing Blow');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Into the Fray');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Trophy Armor');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Vibrobayonet');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Final Stand');
INSERT INTO hero_items(hero,name) VALUES ('Biv Bodhrik','Stay Down');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Modified Blaster');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Tool Kit');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Unstable Device');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Energy Shield');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Structural Weakness');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Gadgeteer');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Power Converter');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Adrenaline Injector');
INSERT INTO hero_items(hero,name) VALUES ('Saska Teft','Remote Distribution');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','All-Weather Rifle');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','Combat Spotter');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','Scouting Report');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','Overwatch');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','Spectrum Scanner');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','Scout’s Guidance');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','Study of Enemies');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','Coordinated Attack (Loku)');
INSERT INTO hero_items(hero,name) VALUES ('Loku Kanoloa','Mon Cala Special Forces');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Sidearm Blaster');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Bacta Injector');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Improper Procedure');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Field Surgeon');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Fuel Injection');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Adrenal Vapor');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Miracle Worker');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Bacta Radiator');
INSERT INTO hero_items(hero,name) VALUES ('MHD-19','Combat Override');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','Military Blaster');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','Combat Momentum');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','Create Opening');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','K’tara Maneuver');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','Student of Battle');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','Point Blank Shot');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','Improvised Cover');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','Master Operative (Verena)');
INSERT INTO hero_items(hero,name) VALUES ('Verena Talos','Combat Mastery');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Heirloom Dagger');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Elusive Agent');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Covert Operative');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Blindside');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Falling Leaf');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Shrouded Lightsaber');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Force Illusion (Davith)');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Embody the Force');
INSERT INTO hero_items(hero,name) VALUES ('Davith Elso','Fell Swoop');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Diplomat''s Blaster');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Company of Heroes');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Sonic Bellow');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Professional Aide');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Rebel Propaganda');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Double Agent');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Solidarity');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Lead from the Front');
INSERT INTO hero_items(hero,name) VALUES ('Murne Rin','Waylay');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Bodyguard Rifle');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Get Down');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Keep Up');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Stay Behind Me');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Mutual Destruction');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Brute Strength');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Hold Still');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Don''t Make me Hurt You');
INSERT INTO hero_items(hero,name) VALUES ('Onar Koma','Black Sun Armor');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','Duelist''s Blade');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','Responsiveness');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','All-Out Attack');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','Smoke Bombs');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','Proximity Strike');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','Swords Dance');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','Remote Detonator');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','Full Sweep');
INSERT INTO hero_items(hero,name) VALUES ('Shyla Varad','Deadly Grace');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Hair-Trigger Pistol');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Pinpoint Shot');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Shot on the Run');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Sharpshooter');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Battlefield Experience');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Dead On');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Off-Hand Blaster');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Rapid Fire');
INSERT INTO hero_items(hero,name) VALUES ('Vinto Hreeda','Merciless (Vinto)');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','MGL-9 "Boomer"');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','Charging Up');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','Leave No One Behind');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','Bank Shot');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','Shrapnel Rounds');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','Repeater Cannon');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','Structural Exploitation');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','Thermal Explosions');
INSERT INTO hero_items(hero,name) VALUES ('Drokkatta','Wookiee Wrath');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Vibro-Claws');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Balanced Approach');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Forward Momentum');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Scout''s Loadout');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Slicer''s Upgrades');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Explosive Reflexes');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Mutual Progression');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Leaping Slash');
INSERT INTO hero_items(hero,name) VALUES ('Jarrod Kelvin','Mechanical Master');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Service Rifle');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Auxiliary Training');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Inch By Inch');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Combat Logistics');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Dig In');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Fire Support Specialist');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Opportunist');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Self-sufficient');
INSERT INTO hero_items(hero,name) VALUES ('Ko-Tun Feralo','Squad Cohesion');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','DC-15S Blaster');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','Covering Fire (CT-1701)');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','Reload');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','Pin Them Down');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','Strafing Run');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','Squad Tactics');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','Weakness Identified');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','Concentrate Fire');
INSERT INTO hero_items(hero,name) VALUES ('CT-1701','Wild Fire');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Reinforced Cyberarm');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Aryx Variation');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Mynock Strike');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Dianoga Sweep');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Gundark Throw');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Acklay Counter');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Dragonsnake Variation');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Fluidity');
INSERT INTO hero_items(hero,name) VALUES ('Tress Hacnua','Krayt Dragon Fury');
