CREATE TABLE imperial_classes(
id INTEGER PRIMARY KEY
   class     VARCHAR(64) NOT NULL
  ,expansion VARCHAR(32) NOT NULL
  ,name      VARCHAR(64) NOT NULL
  ,expansion_id INTEGER
);
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Show of Force');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Combat Medic');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Riot Grenades');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Assault Armor');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Endless Ranks');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Shock Troopers');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Sustained Fire');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Combat Veterans');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Military Might','Core Set','Shock and Awe');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Experimental Arms');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Jetpacks');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Technical Support');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Failsafe');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Hidden Detonators');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Cloaking Device');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Arc Blasters');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Superior Augments');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Technological Superiority','Core Set','Adaptive Weapons');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','Prey Upon Doubt');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','Savage Weaponry');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','Surgical Strike');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','Heavy Pressure');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','Exploit Weakness');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','Executioner');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','Weary Target');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','Oppression');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Subversive Tactics','Core Set','No Quarter');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Field Officer');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Supervisory Agent');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Press On');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Strategic Planning');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Noble Sacrifice');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Imperial Dedication');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Field General');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Optimal Tactics');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Inspiring Leadership','Twin Shadows','Lead By Example');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Strike Force');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Strike Force');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Pinpoint Accuracy');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Sharpshooters');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Knowledge of Attack');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Versatile Attack');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Assassins');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Exacting Strike');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Find the Weakness');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Precision Training','Return to Hoth','Single-Minded');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Explosive Munitions');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Explosive Munitions');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Armor Corps');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Automated Repairs');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Explosive Entry');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Heavy Firepower');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Mortar');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Reactive Armor');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Power to Shields');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Armored Onslaught','Return to Hoth','Rapid Dominance');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','In the Shadows');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','Shadow Corps');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','Stealth');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','Shadow Armor');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','Surprise Attack');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','Execution Squad');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','Strategic Redeployment');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','True Shadow');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Imperial Black Ops','The Bespin Gambit','Versatility');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Wanted: Dead');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Scouted');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Vendetta');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Cheap Shot');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Savage Motivation');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Nowhere to Hide');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Nowhere to Run');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Guild Hunters');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Hutt Mercenaries','Jabba''s Realm','Most Wanted');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Inspirational');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Powerful Foes');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Fearsome Presence');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Prepare the Ambush');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','I''m on the Leader');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Ringleader');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Leave Them to Me');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Punishing Force');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Indomitable');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Nemeses','Jabba''s Realm','Devastating Legion');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','Manifest Aggression');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','Dark Resurgence');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','Embrace Fear');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','Supernatural Vigor');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','Embrace Anger');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','Embrace Hate');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','Unnatural Abilities');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','Embrace Suffering');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Power of the Dark Side','Heart of the Empire','The Power of Passion');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Active Surveillance');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Shielded');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Blaster Emplacements');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Remote Activation');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Mechanical Protocol');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Electromagnetic Disruptors');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Infrared Scanners');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Overclock');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Reactive Defenses','Heart of the Empire','Targeting Sensors');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','Commence Landing');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','Personal Flagship');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','Redouble Our Efforts');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','Implacable');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','TIE Landers');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','Tactical Mastery');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','TIE Fighter Patrol');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','Indomitable Force');
INSERT INTO imperial_classes(class,expansion,name) VALUES ('Overwhelming Oppression','Tyrants of Lothal','Limitless Arsenal');
