CREATE TABLE items(
id INTEGER PRIMARY KEY,
   card_name VARCHAR(26) NOT NULL
  ,expansion VARCHAR(35)
  ,tier      VARCHAR(6) NOT NULL,
  expansion_id integer
);
INSERT INTO items(card_name,expansion,tier) VALUES ('Armored Gauntlets','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Balanced Hilt','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Combat Coat','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('DH-17','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('DL-44','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('E-11','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Extended Haft','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Marksman Barrel','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Portable Medkit','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Survival Gear','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Tactical Display','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Vibroblade','Core Set','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Tatooine Hunting Rifle','Twin Shadows','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Gaffi Stick','Twin Shadows','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('DDC Defender','Return to Hoth','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Vibroknife','Return to Hoth','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Under-Barrel HH-4','Return to Hoth','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Vibrosword','The Bespin Gambit','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Shadowsilk Cloak','The Bespin Gambit','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Bacta Pump','Jabba''s Realm','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Emergency Injector','Jabba''s Realm','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Hand Cannon','Jabba''s Realm','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Charge Pistol','Heart of the Empire','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Charged Ammo Pack','Heart of the Empire','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Responsive Armor','Heart of the Empire','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Combat Vambrace','Tyrants of Lothal','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Punch Dagger','Tyrants of Lothal','Tier 1');
INSERT INTO items(card_name,expansion,tier) VALUES ('Combat Coat','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('A280','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('T-21','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('434 "Deathhammer"','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Vibro Knucklers','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('BD-1 Vibro-Ax','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('High-Impact Guard','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Spread Barrel','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Overcharger','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Laminate Armor','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Extra Ammunition','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Slicing Tools','Core Set','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('EE-3 Carbine',NULL,'Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Plasma Cell',NULL,'Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Environment Hazard Suit','Return to Hoth','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Stun Baton',NULL,'Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Cybernetic Arm',NULL,'Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('R5 Astromech','The Bespin Gambit','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Weighted Head','The Bespin Gambit','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('DT-12 Heavy Blaster Pistol','Greedo Villain Pack','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Bolt Upgrade','Jabba''s Realm','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Double Vibrosword','Jabba''s Realm','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Energized Hilt','Jabba''s Realm','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Focusing Beam','Heart of the Empire','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Hunter''s Rifle','Heart of the Empire','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Polearm','Heart of the Empire','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('E-11D','Tyrants of Lothal','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Mandalorian Helmet','Tyrants of Lothal','Tier 2');
INSERT INTO items(card_name,expansion,tier) VALUES ('Pulse Cannon','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('DXR-6','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Sporting Blaster','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Force Pike','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Laminate Armor','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Personal Shields','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Reinforced Helmet','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Combat Visor','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Combat Knife','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Shock Emitter','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Disruption Cell','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Telescoping Sights','Core Set','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Hidden Blade','Twin Shadows','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('DLT-19','Twin Shadows','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Valken-38 Carbine',NULL,'Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Vibrogenerator',NULL,'Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Concussion Grenades',NULL,'Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Sniper Scope','The Bespin Gambit','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Disruptor Pistol','The Bespin Gambit','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Ancient Lightsaber','Obi Wan Kenobi Ally Pack','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Electrostaff','The Grand Inquisitor Villain Pack','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Admiral''s Uniform','Jabba''s Realm','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Modified Energy Cannon','Jabba''s Realm','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Ryyk Blades','Jabba''s Realm','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('A-12 Sniper Rifle','Heart of the Empire','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Power Charger','Heart of the Empire','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Supply Pack','Heart of the Empire','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Bo-rifle','Tyrants of Lothal','Tier 3');
INSERT INTO items(card_name,expansion,tier) VALUES ('Plastoid Armor','Tyrants of Lothal','Tier 3');
